## importing libraries

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## data preprocessing

### training image preprocessing

In [6]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 60972 files belonging to 33 classes.


### validation image preprocessing

In [7]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,

    verbose=True,
)

Found 60972 files belonging to 33 classes.


In [8]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 33), dtype=tf.float32, name=None))>

In [9]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break
    

tf.Tensor(
[[[[154.5  143.5  149.5 ]
   [156.   145.   151.  ]
   [181.   170.   176.  ]
   ...
   [165.75 154.75 160.75]
   [171.   160.   166.  ]
   [172.   161.   167.  ]]

  [[155.25 144.25 150.25]
   [147.75 136.75 142.75]
   [166.75 155.75 161.75]
   ...
   [163.5  152.5  158.5 ]
   [168.5  157.5  163.5 ]
   [171.5  160.5  166.5 ]]

  [[153.   142.   148.  ]
   [155.5  144.5  150.5 ]
   [150.75 139.75 145.75]
   ...
   [176.5  165.5  171.5 ]
   [175.75 164.75 170.75]
   [167.   156.   162.  ]]

  ...

  [[159.5  148.5  156.5 ]
   [152.5  141.5  149.5 ]
   [171.75 160.75 168.75]
   ...
   [163.75 153.75 162.75]
   [161.75 151.75 160.75]
   [160.5  150.5  159.5 ]]

  [[165.75 154.75 162.75]
   [172.5  161.5  169.5 ]
   [179.5  168.5  176.5 ]
   ...
   [163.25 153.25 162.25]
   [167.25 157.25 166.25]
   [169.25 159.25 168.25]]

  [[161.25 150.25 158.25]
   [162.5  151.5  159.5 ]
   [164.   153.   161.  ]
   ...
   [170.   160.   169.  ]
   [169.25 159.25 168.25]
   [166.5  156.5  16

##Building model

In [22]:
from tensorflow.keras.layers import Dense,Conv2D
from tensorflow.keras.models import Sequential

In [23]:
model = Sequential()

## Building Convolution Layer

In [18]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape={128,128,3}))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 128, 3)

In [16]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape={128,128,3}))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 128, 3)

In [19]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape={128,128,3}))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 128, 3)

In [20]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape={128,128,3}))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 128, 3)

In [ ]:
model.add(Flatten())

In [ ]:
model.add(Dense(units=1024,activation='relu'))

###Compiling model


In [ ]:
model.compile(optimizes='adam',loss='categorical crossentropy',metrics={'accuracy'})

In [ ]:
model.summary()